# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  filter_sets:
    thumb:
      quality: 100
      filters:
        thumbnail:
          size:           [348, 196]
          mode:           outbound
    medium:
      quality: 100
      filters:
        thumbnail:
          size:           [730, 411]
          mode:           outbound
    home:
      quality: 100
      filters:
        thumbnail:
          size:           [230, 120]
          mode:           outbound